{
 "title": "General Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Exporter List",
   "type": "table",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Servers Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up==0) OR on() vector(0)" }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate!=\"pending\"}) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "ALERTS{alertstate!=\"pending\"}"
    }
   ]
  }
 ]
}