services:
  mariadb:
    image: mariadb:10
    environment:
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_RANDOM_ROOT_PASSWORD: 1
    command: ["--skip-ssl", "--skip-networking=0"]
    volumes:
      - .data/:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: "30s"
      timeout: "10s"
      retries: 5

  zabbix.server.init:
    image: zabbix/zabbix-server-mysql:alpine-7.4-latest
    environment:
      DB_SERVER_HOST: "mariadb"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      DB_TLS_CONNECT: "disable"
    command: |
      bash -c '
      zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | \
      mariadb --ssl=0 -h$${DB_SERVER_HOST} -u$${MYSQL_USER} -p$${MYSQL_PASSWORD} $${MYSQL_DATABASE} || exit 0
      '
    depends_on:
      mariadb:
        condition: service_healthy

  zabbix.server:
    image: zabbix/zabbix-server-mysql:alpine-7.4-latest
    environment:
      DB_SERVER_HOST: "mariadb"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      DB_TLS_CONNECT: "disable"
    ports:
      - "10050:10050"
      - "10051:10051"
    depends_on:
      zabbix.server.init:
        condition: service_completed_successfully
    restart: unless-stopped

  zabbix.frontend:
    image: zabbix/zabbix-web-apache-mysql:alpine-7.4-latest
    environment:
      DB_SERVER_HOST: "mariadb"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      ZBX_SERVER_HOST: "zabbix.server"
      PHP_TZ: ${TZ}
      DB_TLS_CONNECT: "disable"
    depends_on:
      zabbix.server:
        condition: service_started
    ports:
      - "80:8080"
      - "443:8443"
    restart: unless-stopped
