services:
  prometheus:
    image: prom/prometheus:main
    tty: true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    ports:
      - "9090:9090"
    volumes:
      - "prometheus_data:/prometheus:Z"
      - "./config:/prometheus"
      - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./config/prometheus/rules.yml:/etc/rules.yml"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--log.level=debug'
    networks:
      - intranet

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:latest
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "grafana_data:/var/lib/grafana:Z"
      - "./config/grafana/data-sources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./config/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml"
      - "./config/grafana/general-status-dashboard.yml:/etc/grafana/provisioning/dashboards/general-status-dashboard.json"
      - "./config/grafana/node-exporter-dashboard.yml:/etc/grafana/provisioning/dashboards/node-exporter-full-dashboard.json"
    networks:
      - intranet

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  intranet:
    driver: bridge
