services:
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    tty: true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    ports:
      - "9090:9090"
    volumes:
      - "prometheus_data:/prometheus:Z"
      - "./config:/prometheus"
      - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./config/prometheus/rules.yml:/etc/rules.yml"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--log.level=debug'
    networks:
      - intranet

  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana:latest
    container_name: grafana
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "grafana_data:/var/lib/grafana:Z"
      - "./config/grafana/data-sources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./config/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml"
      - "./config/grafana/general-status-dashboard.yml:/etc/grafana/provisioning/dashboards/general-status-dashboard.json"
      - "./config/grafana/node-exporter-dashboard.yml:/etc/grafana/provisioning/dashboards/node-exporter-full-dashboard.json"
    networks:
      - intranet

  alertmanager:
    depends_on:
      - prometheus
    image: prom/alertmanager:main
    container_name: alertmanager
    user: "1000:1000"
    tty: true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1024m"
    ports:
      - "9093:9093"
    volumes:
      - "alertmanager_data:/data:Z"
      - "./config/alertmanager/config.yml:/alertmanager/alertmanager.yml"
      - "./config/alertmanager/templates:/alertmanager/templates"
    command:
      - '--config.file=/alertmanager/alertmanager.yml'
      - '--cluster.advertise-address=0.0.0.0:9093'
      - '--storage.path=/data'
      - '--log.level=debug'
    networks:
      - intranet

volumes:
  prometheus_data: {}
  grafana_data: {}
  alertmanager_data: {}

networks:
  intranet:
    driver: bridge
