services:
  backend:
    volumes:
      - ${BACKEND_CONTEXT:-../../auth-service}:/var/www/html

  web_tienda:
    volumes:
      - ${TIENDA_CONTEXT:-../../tienda-web}:/app

  web_publicadores:
    volumes:
      - ${PUBLICADORES_CONTEXT:-../../publicadores-web}:/app

